@startchen

left to right direction

<style>
.grey {
BackGroundColor Grey
FontColor White
}
</style>

/'
//////////////////////////////////////////
=================ENTITIES=================
//////////////////////////////////////////
'/

entity product {
	id : Long <<key>>
	name : varchar
	description : varchar
	price : Decimal
	created_at : Date
	updated_at : Date
}

entity image{
    id : Long <<key>>
    url : varchar
    product_id : Long <<fk>>
}

entity customer {
	id : Long <<key>>
	name : varchar
	credentials_id : long <<FK>>
	created_at : Date
    updated_at : Date
}

entity address {
    id: Long <<key>>
    street : varchar
    number : varchar
    complement : varchar
    customer_id : Long <<FK>>
    city_id : Long
    created_at : Date
    updated_at : Date
}

entity city {
    id : Long <<key>>
    name : varchar
    state_id : Long <<key>>
}

entity state {
    id : Long <<key>>
    name : varchar
    acronym : varchar <<key>>
}

entity email {
	id : Long <<key>>
	email : varchar
	customer_id : Long <<FK>>
	created_at : Date
    updated_at : Date
}

entity credentials {
	id : Long <<key>>
	username : varchar
	password : varchar
	created_at : Date
    updated_at : Date
}

entity cart {
	id : Long <<key>>
	customer_id : Long <<key>>	
}

entity "products_cart" as pc {
	id : Long <<key>>
	product_id : Long <<key>>
	cart_id : Long <<key>>
}

entity warehouse {
    id : Long <<key>>
    city_id : Long
}

entity inventory {
    id : Long <<key>>
    product_id : Long <<key>>
    warehouse_id : Long <<key>>
    quantity : int
    created_at : Date
    updated_at : Date
}




/'
//////////////////////////////////////////
=================ENTITIES=================
//////////////////////////////////////////

===============================================
===============================================

///////////////////////////////////////////////
=================RELATIONSHIPS=================
///////////////////////////////////////////////
'/


relationship "has" as EMAIL_CUSTOMER <<grey>>{
}

email -N- EMAIL_CUSTOMER
customer -1- EMAIL_CUSTOMER

relationship "has" as CUSTOMER_CREDENTIALS <<grey>> {
}

customer -1- CUSTOMER_CREDENTIALS
credentials -1- CUSTOMER_CREDENTIALS


relationship "has" as CUSTOMER_CART <<grey>> {
}

customer -1- CUSTOMER_CART
cart -1- CUSTOMER_CART

relationship "contains" as PC_PRODUCT <<grey>> {
}

product -N- PC_PRODUCT
pc -N- PC_PRODUCT

relationship "contains" as PC_CART <<grey>> {
}

cart -N- PC_CART
pc -N- PC_CART

relationship "contains" as PRODUCT_INVENTORY <<grey>> {
}

product -N- PRODUCT_INVENTORY
inventory -N- PRODUCT_INVENTORY

relationship "has" as INVENTORY_WAREHOUSE <<grey>> {
}

warehouse -1- INVENTORY_WAREHOUSE
inventory -1- INVENTORY_WAREHOUSE

relationship "belongs to" as CITY_STATE <<grey>> {
}
city -N- CITY_STATE
state -1- CITY_STATE

relationship "contains" as ADDRESS_CITY <<grey>>{
}
address -N- ADDRESS_CITY
city -1- ADDRESS_CITY

relationship "has" as CUSTOMER_ADDRESS <<grey>> {
}
customer -N- CUSTOMER_ADDRESS
address -1- CUSTOMER_ADDRESS

relationship "belongs to" as IMAGE_PRODUCT <<grey>> {
}
product -1- IMAGE_PRODUCT
image -N- IMAGE_PRODUCT

relationship "located at" as WAREHOUSE_CITY <<grey>>{
}
city -1- WAREHOUSE_CITY
warehouse -N- WAREHOUSE_CITY
@endchen
